### ISSUE TITLE
Handle failed logins?

### ISSUE THREAD

**Issue by fiveisprime** [lostintangent/az-login#5]
In reference to [this issue](https://github.com/serverless/serverless-azure-functions/issues/68)

The login method doesn't appear to catch any errors; however, there's a potential
for the authentication functionality to [reject if the credentials are invalid](https://github.com/lostintangent/az-login/blob/master/index.js#L33).

**Comment by lostintangent** [comment]
Ah I think I see the issue here. The authentication logic [wraps the underlying login calls with a `try/catch`](https://github.com/lostintangent/az-login/blob/master/index.js#L30), however, those login methods are async, so the `catch` would never get hit. We'd need to update [this logic](https://github.com/lostintangent/az-login/blob/master/index.js#L75) to actually check for an async error, and reject the returned `Promise`.

**Comment by fiveisprime** [comment]
Also interesting is that issue I linked above has mention of some changes to the
error handling, but those changes (f829c7b) were reverted in 623b7f3 somehow. :(

**Comment by lostintangent** [comment]
Hmm, interesting. Yeah I can add that logic back in. It looks like I mistakenly removed it while refactoring the subscription detection behavior.

**Comment by fiveisprime** [comment]
Fix landed in az-login@0.2.1
